version: '3'
services:
  b1ngo:
    container_name: b1ngo
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - postgresql
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
  postgresql:
    container_name: postgresql_b1ngo
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"